// The built-in ingredient library: every Spoonacular ingredient plus curated everyday groceries
// (see ./library/data.ts, generated by scripts/build-ingredient-library.mjs).
//
// Pure module (no Node or Next APIs). The server uses it to categorize typed names; the browser
// imports it lazily for autocomplete. Lookup structures are built once, on first use.
import { CATEGORY_KEYS, ROWS, UNIT_SETS } from "./library/data"
import { createMatcher, type Matcher } from "./library/match"
import { foldText, ingredientWords, normalizeIngredientName as normalizeKey, singularizeWord } from "./library/normalize"
import { categoryByRules, isNonFoodWords } from "./library/rules"
import type { Category, CatalogEntry } from "./types"

/**
 * Stable key for matching names (also stored as category_overrides.ingredient_key, max 80 chars):
 * lowercase ASCII words, punctuation dropped, filler words dropped (fresh, organic, large, chopped …),
 * each word singular. "Fresh Tomatoes" → "tomato", "Whole Milk" → "whole milk".
 */
export function normalizeIngredientName(name: string): string {
  return normalizeKey(name)
}

/**
 * Best library match for a typed name, or null. An exact name or alias first, then the most
 * specific entry whose words the name contains, preferring one that ends the way the name does:
 * "boneless skinless chicken breasts" → chicken breast, "kerrygold unsalted butter" → unsalted butter.
 * Household things never match a food by their words ("coffee filters" isn't coffee).
 */
export function findIngredient(name: string): CatalogEntry | null {
  const key = normalizeKey(name)
  if (!key) return null
  const match = getMatcher().find(key)
  if (!match) return null
  if (!match.exact && isNonFoodWords(ingredientWords(name).join(" "))) return null
  return library().entries[match.entry]
}

/**
 * Autocomplete: entries whose name or alias has words starting with what's typed, in order
 * ("chi bre" → chicken breast). Best first:
 *   1. the whole query names the entry ("tomatoes", "scallions", "fresh basil");
 *   2. then by commonness tier, where matching only a later word of the name costs one tier and
 *      matching only an alias two, so everyday items come first ("bre" → bread, bread flour, …,
 *      white bread, chicken breast; "chi" → chicken before chia seeds);
 *   3. ties: the name starting with the query before a later word or an alias, then the more
 *      common entry, then the shorter name.
 * Each entry appears once, under its canonical name. A query nothing starts like falls back to
 * findIngredient ("kerrygold unsalted butter" → unsalted butter). "" → [].
 */
export function searchIngredients(query: string, limit = 8): CatalogEntry[] {
  if (!(limit > 0)) return []
  const words = queryWords(foldText(query))
  if (words.length === 0) return []

  const { entries } = library()
  const hits = new Map<number, Hit>()
  const exact = getMatcher().find(normalizeKey(query))
  if (exact?.exact) addHit(hits, exact.entry, EXACT)

  collectPrefixHits(words, hits)
  if (hits.size === 0) {
    // "organic chi", "large eg": try again without the descriptive words.
    const plain = queryWords(normalizeKey(query))
    if (plain.length > 0 && plain.join(" ") !== words.join(" ")) collectPrefixHits(plain, hits)
  }

  const ranked = [...hits.values()].sort(compareHits)
  const results = ranked.slice(0, limit).map((hit) => entries[hit.entry])
  if (results.length < limit) {
    // Nothing starts like this, but the words name something ("kerrygold unsalted butter").
    const best = findIngredient(query)
    if (best && !results.includes(best)) results.push(best)
  }
  return results
}

/** The entry with this Spoonacular id (its own, or one of the ids folded into it), or null. */
export function getIngredientById(id: number): CatalogEntry | null {
  return library().byId.get(id) ?? null
}

/**
 * Keyword guess for names the library doesn't know: "oat milk" → dairy, "frozen dumplings" → frozen,
 * "sriracha mayo" → condiments, "kombucha" → beverages, "dish soap" → other. "other" when nothing fits.
 */
export function guessCategory(name: string): Category {
  return categoryByRules(ingredientWords(name).join(" ")) ?? "other"
}

// ── The library ───────────────────────────────────────────────────────────────────────────────

type Library = {
  entries: readonly CatalogEntry[]
  /** Commonness per entry: 1 staple … 5 rare. */
  tiers: readonly number[]
  byId: ReadonlyMap<number, CatalogEntry>
}

let libraryCache: Library | null = null
let matcherCache: Matcher | null = null
let searchCache: SearchIndex | null = null

/** Parses ROWS (name|category|tier|units|id|aliases|more ids, see ./library/data.ts). */
function library(): Library {
  if (libraryCache) return libraryCache
  const unitSets = UNIT_SETS.map((set) => Object.freeze(set.split(",")) as string[])
  const entries: CatalogEntry[] = []
  const tiers: number[] = []
  const owner = new Map<number, number>() // Spoonacular id → entry index
  const extraIds: [id: number, entry: number][] = []

  for (const line of ROWS.split("\n")) {
    if (!line) continue
    const [name, category, tier, units, id, aliases = "", moreIds = ""] = line.split("|")
    const entry: CatalogEntry = {
      id: id ? Number(id) : null,
      name,
      category: CATEGORY_KEYS[Number(category)] as Category,
      aliases: aliases ? aliases.split(",") : [],
      units: unitSets[Number(units)],
    }
    Object.freeze(entry.aliases)
    const index = entries.push(Object.freeze(entry)) - 1
    tiers.push(Number(tier))
    if (entry.id !== null) {
      // Spoonacular gives a few ingredients one id ("cream", "heavy cream"): the more common entry keeps it.
      const known = owner.get(entry.id)
      if (known === undefined || tiers[known] > tiers[index]) owner.set(entry.id, index)
    }
    if (moreIds) for (const more of moreIds.split(",")) extraIds.push([Number(more), index])
  }
  // An entry's own id wins over an id another entry folded in.
  for (const [id, index] of extraIds) if (!owner.has(id)) owner.set(id, index)

  const byId = new Map<number, CatalogEntry>()
  for (const [id, index] of owner) byId.set(id, entries[index])
  libraryCache = { entries, tiers, byId }
  return libraryCache
}

function getMatcher(): Matcher {
  if (matcherCache) return matcherCache
  const { entries, tiers } = library()
  matcherCache = createMatcher(
    entries.flatMap((entry, index) =>
      [entry.name, ...entry.aliases].map((name) => ({ key: normalizeKey(name), entry: index, tier: tiers[index] })),
    ),
  )
  return matcherCache
}

// ── Autocomplete ──────────────────────────────────────────────────────────────────────────────

/** How a query matched a name. Lower is better. */
const EXACT = 0
const NAME_START = 1
const LATER_WORD = 2
const ALIAS = 3
type Kind = typeof EXACT | typeof NAME_START | typeof LATER_WORD | typeof ALIAS

/** Tiers a weaker match costs: a tier-1 entry matched on a later word ranks with tier-2 name starts. */
const KIND_COST: Record<Kind, number> = { [EXACT]: -100, [NAME_START]: 0, [LATER_WORD]: 1, [ALIAS]: 2 }

type Hit = { entry: number; kind: Kind; score: number }

type SearchIndex = {
  /** Entry index of each searchable name (every entry name and alias). */
  nameEntry: Int32Array
  /** 1 when the name is an alias. */
  nameIsAlias: Uint8Array
  /** Folded words of each name, and each word singular. */
  nameWords: string[][]
  nameSingular: string[][]
  /** Every distinct word (folded and singular forms), sorted, for prefix ranges. */
  vocab: string[]
  /** postings[i]: the names containing vocab[i], encoded as name * 64 + word position. */
  postings: number[][]
}

const MAX_WORDS = 63

function searchIndex(): SearchIndex {
  if (searchCache) return searchCache
  const { entries } = library()
  const nameEntry: number[] = []
  const nameIsAlias: number[] = []
  const nameWords: string[][] = []
  const nameSingular: string[][] = []
  const byWord = new Map<string, number[]>()

  const post = (word: string, code: number) => {
    const list = byWord.get(word)
    if (!list) byWord.set(word, [code])
    else if (list[list.length - 1] !== code) list.push(code)
  }

  entries.forEach((entry, index) => {
    const names = [entry.name, ...entry.aliases]
    names.forEach((name, nameIndex) => {
      // Names are stored lowercase; most are plain ASCII already.
      const words = (/^[a-z0-9]+(?: [a-z0-9]+)*$/.test(name) ? name : foldText(name)).split(" ").slice(0, MAX_WORDS)
      if (!words[0]) return
      const singular = words.map(singularizeWord)
      const id = nameEntry.length
      nameEntry.push(index)
      nameIsAlias.push(nameIndex === 0 ? 0 : 1)
      nameWords.push(words)
      nameSingular.push(singular)
      words.forEach((word, position) => {
        post(word, id * 64 + position)
        if (singular[position] !== word) post(singular[position], id * 64 + position)
      })
    })
  })

  const vocab = [...byWord.keys()].sort()
  searchCache = {
    nameEntry: Int32Array.from(nameEntry),
    nameIsAlias: Uint8Array.from(nameIsAlias),
    nameWords,
    nameSingular,
    vocab,
    postings: vocab.map((word) => byWord.get(word) ?? []),
  }
  return searchCache
}

type QueryWord = { text: string; singular: string }

function queryWords(folded: string): QueryWord[] {
  if (!folded) return []
  return folded
    .split(" ")
    .slice(0, MAX_WORDS)
    .map((text) => ({ text, singular: singularizeWord(text) }))
}

/**
 * Whether a typed word matches a word of a name: a prefix of it or of its singular ("chi" →
 * chicken, "strawberry" → strawberries), or, for a finished plural, the same word ("peas" → pea,
 * but not peanut).
 */
function wordMatches(query: QueryWord, word: string, singular: string): boolean {
  if (word.startsWith(query.text) || singular.startsWith(query.text)) return true
  return query.singular !== query.text && (word === query.singular || singular === query.singular)
}

/** First index in the sorted list that is >= value. */
function lowerBound(list: readonly string[], value: string): number {
  let low = 0
  let high = list.length
  while (low < high) {
    const middle = (low + high) >>> 1
    if (list[middle] < value) low = middle + 1
    else high = middle
  }
  return low
}

function collectPrefixHits(words: readonly QueryWord[], hits: Map<number, Hit>): void {
  const index = searchIndex()
  const { tiers } = library()
  const first = words[0]
  const seen = new Set<number>()

  const visit = (code: number) => {
    if (seen.has(code)) return
    seen.add(code)
    const name = Math.floor(code / 64)
    const position = code % 64
    const nameWords = index.nameWords[name]
    const singular = index.nameSingular[name]
    if (!wordMatches(first, nameWords[position], singular[position])) return
    // The other typed words must match later words of the same name, in order.
    let next = position + 1
    for (let i = 1; i < words.length; i++) {
      while (next < nameWords.length && !wordMatches(words[i], nameWords[next], singular[next])) next++
      if (next >= nameWords.length) return
      next++
    }
    const entry = index.nameEntry[name]
    const kind: Kind = index.nameIsAlias[name] ? ALIAS : position === 0 ? NAME_START : LATER_WORD
    addHit(hits, entry, kind, tiers[entry])
  }

  // Vocabulary words starting with the first typed word …
  for (let i = lowerBound(index.vocab, first.text); i < index.vocab.length; i++) {
    if (!index.vocab[i].startsWith(first.text)) break
    for (const code of index.postings[i]) visit(code)
  }
  // … and, for a finished plural ("cherries"), the singular word itself.
  if (first.singular !== first.text) {
    const i = lowerBound(index.vocab, first.singular)
    if (index.vocab[i] === first.singular) for (const code of index.postings[i]) visit(code)
  }
}

function addHit(hits: Map<number, Hit>, entry: number, kind: Kind, tier = 1): void {
  const hit: Hit = { entry, kind, score: tier + KIND_COST[kind] }
  const known = hits.get(entry)
  if (!known || compareHits(hit, known) < 0) hits.set(entry, hit)
}

function compareHits(a: Hit, b: Hit): number {
  if (a.score !== b.score) return a.score - b.score
  if (a.kind !== b.kind) return a.kind - b.kind
  const { entries, tiers } = library()
  if (tiers[a.entry] !== tiers[b.entry]) return tiers[a.entry] - tiers[b.entry]
  const nameA = entries[a.entry].name
  const nameB = entries[b.entry].name
  if (nameA.length !== nameB.length) return nameA.length - nameB.length
  return nameA < nameB ? -1 : nameA > nameB ? 1 : 0
}

// In the browser this module is loaded when someone starts adding food: build the lookups now,
// so the first keystroke doesn't wait. The server builds them on first use.
if (typeof window !== "undefined") {
  searchIndex()
  getMatcher()
}
